cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/MyUserDTO.java

Ref https://github.com/ClouDesire/backend/issues/4826

Add array of roles that user can create

---

cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/ProductDTO.java

Add boolean if product is service

---

cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/csv/OrderCsvDTO.java

Reverts ClouDesire/java-api-client#33

Revert "Remove price property from order CSV"

---

cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/CloudesireClient.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/MyUserDTO.java

User birthday short date format

---

cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/EnvironmentDTO.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/MyUserDTO.java

https://github.com/ClouDesire/support/issues/1470

Add keycloak integration

---

cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/CloudesireClient.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/MultipartFactory.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/CompanyLogoApi.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/ProductFileApi.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/VMConfigurationApi.java

Deprecate previous getUploadPayload method on main client class

Add MultipartFactory for file uploads

---

cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/OrderInputDTO.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/UrlEntityDTO.java

Avoid ApiModelProperty on field with non-primitive types

---

cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/PageRequestDTO.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/UrlEntityDTO.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/enums/SortDirection.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/filters/InvoiceFilter.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/filters/ReportFilter.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/filters/ResellingReportFilter.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/filters/SubscriptionFilter.java

Document GET parameters

---

cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/ProductApi.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/query/BaseQuery.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/query/PageRequestQuery.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/query/ProductQuery.java
cmw-dto/src/main/java/com/liberologico/cloudesire/cmw/model/dto/PageRequestDTO.java

Simplify ProductApi.getAll methods using an unique QueryMap object

Add ProductQuery object to ProductApi

---

cloudesire-api-client/pom.xml
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/CloudesireClientCallExecutor.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/response/CallResponse.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/response/Pagination.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/CloudesireClientTest.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/Httpbin.java
cloudesire-api-client/src/test/resources/logback-test.xml

Response headers available with an alternate executor method

Full response executor

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/ApiVersion.java
cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/InvoiceDTO.java
cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/PaymentMethodDTO.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/InvoiceApi.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/UserApi.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/CloudesireClientTest.java

https://github.com/ClouDesire/backend/pull/5854

Support Stripe SCA

---

base-api-client/src/main/java/com/cloudesire/platform/apiclient/baseclient/AbstractCloudesireClient.java
base-api-client/src/main/java/com/cloudesire/platform/apiclient/baseclient/Timeout.java
base-api-client/src/main/java/com/cloudesire/platform/apiclient/baseclient/TimeoutConfig.java

Fix https://github.com/ClouDesire/java-api-client/issues/340

Change default timeouts

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

https://github.com/ClouDesire/support/issues/2621

Add geocall feature toggle to enable custom geocall records

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

https://github.com/ClouDesire/support/issues/2636

Add feature toggle for self-registration

---

.circleci/config.yml

Use common-backend context

---

.circleci/config.yml

Never fail

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

ClouDesire/support/issues/3715
ClouDesire/backend/pull/6392

Initialize currency conversion map

---

cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/ProceedsReportApi.java

https://github.com/ClouDesire/support/issues/4010#issuecomment-666325377

Add HEAD proceedsReport

---

.circleci/config.yml

Use sonar orb

---

.circleci/config.yml

ref https://github.com/ClouDesire/support/issues/4745

add cloudesire/maven_release job to build workflow

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.9.2

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/ProductVersionDTO.java

the proper way to do  https://github.com/ClouDesire/java-api-client/pull/568

Deprecate productVersion.metadata

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.9.3

---

pom.xml

https://app.circleci.com/pipelines/github/ClouDesire/backend/7538/workflows/6e5832cb-6fd1-4a19-83dc-31d360d3a76d/jobs/62138

Enable artifact signing only on release branch

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.10.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.11.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.11.1

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.11.2

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.11.3

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/VendorOrderLineDTO.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/api/ProceedsReportApi.java

- Tag live custom costs
- Delete report lines by tag

live report custom costs tag

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.11.4

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.12.1

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/ApiVersion.java
cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/BaseSubscriptionDTO.java
cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/OrderDTO.java

Expose previous billing period end date in order

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.12.2

---

pom.xml

ref https://github.com/ClouDesire/support/issues/6329

Use nexus as maven repository 

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.12.3

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

ref https://github.com/ClouDesire/support/issues/6236

Add feature flags for email billing summaries

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.12.4

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 2.13.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.0.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.0.1

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.0.2

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.1.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.2.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.2.2

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.2.3

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.4.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.5.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.6.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.6.1

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

Release 3.6.2

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

https://github.com/ClouDesire/support/issues/7484

Add feature flag for enabled frontend applications

---

cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/EnvironmentDTO.java

https://github.com/ClouDesire/support/issues/7545

Configure rate limiter defaults in environment

---

cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/CloudesireClient.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/CloudesireClientTest.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/Httpbin.java
cloudesire-api-client/src/test/java/com/cloudesire/platform/apiclient/test/HttpbinBearerResponse.java

https://github.com/ClouDesire/support/issues/7595

Support `Authorization: Bearer` auth header

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

chore: release 3.7.0

---

.mvn/wrapper/maven-wrapper.properties
cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/ApiVersion.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/query/CostsQuery.java
cloudesire-api-client/src/main/java/com/cloudesire/platform/apiclient/query/PageRequestQuery.java

https://github.com/ClouDesire/backend/pull/8396

feat: paginate costs/earnings retrieval

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

chore: release 3.8.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

chore: release 3.9.0

---

base-api-client/pom.xml
cloudesire-api-client-dto/pom.xml
cloudesire-api-client/pom.xml
common-dto/pom.xml
pom.xml

chore: release 3.10.0
